distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 5.1.8
install_time: "Sat Sep 21 15:08:24 2024"
installation_id: "b22ac832-d368-4fbc-ba75-696e668b9583"
rime_version: 1.11.2