distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 5.1.8
install_time: "Wed Jul 10 20:57:38 2024"
installation_id: "8bf2e3e5-6baf-4f31-8ba8-547a19c5f984"
rime_version: 1.11.2
update_time: "Tue Aug 27 08:27:11 2024"